# spring:
#    application:
#           name: CONFIG-DEFAULT






eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka  # Replace with your Eureka server's host and port
  instance:
    prefer-ip-address: true  # Register with the IP address of the instance


